# This code is generated by PyUIbuilder: https://github.com/PaulleDemon/PyUIBuilder
import re
import tkinter as tk
import screen_connector
import start_connection
import threading

dev_dict_list = []


def start_phone_connection(serial, ip):
    connector = screen_connector.ScreenConnector(serial=serial, ip=ip)
    connector.setup_tcpip()
    connector.connect_tcpip()


def refresh():
    menu = select_device_dropdown["menu"]
    menu.delete(0, "end")

    global dev_dict_list
    dev_dict_list = start_connection.get_devices_list_of_dict()
    print(dev_dict_list)
    options = [f"{d['name']} ({d['serial']})" for d in dev_dict_list]

    for option in options:
        menu.add_command(label=option, command=lambda value=option: select_device_dropdown_var.set(value))


def refresh_btn_clicked():
    refresh()


def connect_btn_clicked():
    # get a list of devices currently available to connect.
    global dev_dict_list
    selection = select_device_dropdown_var.get()

    # figure out the serial of the device based on the item selected in the dropdown.
    serial_match = re.search(r".+(\()(.+)(\))", selection)
    if not serial_match:
        warn = "Cannot find the device specified!"
        warninglabel.config(text=warn)
        print(warn)
        return
    serial = serial_match.group(2)

    dev_dict = start_connection.get_device_dict_with_serial(dev_dict_list, serial)
    print(dev_dict)
    connection_thread = threading.Thread(target=start_phone_connection, args=(serial, dev_dict["ip"]))
    connection_thread.daemon = True
    connection_thread.start()
    return


main = tk.Tk()
main.config(bg="#E4E2E2")
main.title("Connect to Phone")

# Main Window
selectdevicelabel = tk.Label(master=main, text="Select Device")
selectdevicelabel.config(bg="#E4E2E2", fg="#000")
selectdevicelabel.pack(side=tk.LEFT, padx=10, pady=10, anchor='nw')

# Drop Down
select_device_dropdown_var = tk.StringVar(value="Select option")
select_device_dropdown = tk.OptionMenu(main, select_device_dropdown_var, "")
select_device_dropdown.config(bg="#fff", fg="#000")
select_device_dropdown.pack(side=tk.LEFT, padx=10, pady=10, anchor='nw')
refresh()

# Connect Button
connectbtn = tk.Button(master=main, text="Connect", command=connect_btn_clicked)
connectbtn.config(bg="#E4E2E2", fg="#000")
connectbtn.pack(side=tk.LEFT, padx=10, pady=10, anchor='nw')

# Refresh Button
connectbtn = tk.Button(master=main, text="Refresh", command=refresh_btn_clicked)
connectbtn.config(bg="#E4E2E2", fg="#000")
connectbtn.pack(side=tk.LEFT, padx=10, pady=10, anchor='nw')

# Warning Label
warninglabel = tk.Label(master=main, text="")
warninglabel.config(bg="#E4E2E2", fg="#000")
warninglabel.pack(side=tk.BOTTOM, padx=10, pady=10, anchor='sw')

main.mainloop()